title: Suvi Korhonen
logo: 


## The commandline-course



## What did I lear? 
### * Week 1: Command-line environment
  * mkdir, cd, mv, wget, ls, emacs, less 

### * Week 2: Navigating a UNIX System
  *gzip, tar, scp
 
  
### * Week 3: Basic Corpus Processing
  * utf-8 encoding, 
  *N files
  *egrep, wc
### * Week 4: Advanced Corpus Processing
  *sed 
  *regular expression
  *UNIX and pipe |
### * Week 5: Scripting and Configuration Files
  *scripts
  *echo, export
  
### * Week 6: Installing and Running Programs
  *sudo, brew
  *pip, uploading using pip
  *creating Makefile and running it
### * Week 7: Version Control
  *version control using Github
  *repository set up, cloning, commit and push changes
### * Final project
  *jekyll, markdown
  
  
  Topics I ...
  
| struggled with| were easy     | meh ðŸ¤· |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |


![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")

at least one list, image and table 
You should write a short overall introduction to the course and one section for every week (for the final week, you can talk about Jekyll and Gihub Pages).
Please use appropriate headers for each section.
You should briefly describe the main content of each week and also briefly reflect on what you learned during the week (maybe 1-3 sentences for reflection)



description: page for me and commandline course
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
